
<h2>Quelles tendances pour la santé digitale en 2020 ?</h2>
<h3>Dans la santé digitale, les tendances technologiques ne disparaissent pas; elles co-existent, alors que la majorité des patients n’en bénéficie pas encore. Des pilotes, des expérimentations, des études cliniques, il y en a.</h3>
<p>Mais les scale-up sont encore rares. Résultat: les systèmes de santé et leur écosystème professionnel doivent se tenir au courant de multiples technologies et jongler avec beaucoup d’incertitudes dans leurs plans opérationnels.</p>

<p>De leur côté, Apple, Amazon, et Google avancent dans le médical et ont l’avantage non seulement de leurs moyens financiers considérables, mais aussi de leurs partenariats importants, des données utilisateurs enregistrées, et de la notoriété de leur marque. Quant aux patients, les sondages successifs révèlent qu’ils sont pragmatiques et donc majoritairement favorables à l’application du digital à la santé. </p>

<p>Comment voir clair parmi les différentes technologies en santé? Une approche est de situer les segments par taille de marché estimée par les cabinets d’étude internationaux dédiés aux nouvelles technologies. Un exercice périlleux certes, mais nous recherchons ici plutôt un ordre de grandeur et non pas le chiffre précis.</p>

<p>Impression 3D, IA et réalité virtuelle 
Commençons par l’impression 3D en santé, dont on sait qu’il avance, grâce à l’actualité portant sur l’impression de tissus et organes humains. Aujourd’hui, il concerne notamment les implants dentaires et chirurgicaux. Le marché est estimé d’atteindre 2,2 milliards d’euros en 2025.</p>

<p>L’intelligence artificielle en santé fascine pour son potentiel de faire mieux que l’être humain, grâce à ses capacités de calcul quasi-illimités. Si la radiologie et la cardiologie sont les deux disciplines les plus avancées, l’IA pourrait intervenir partout où il faut traiter de grands volumes de données, afin d’observer des patterns et corrélations: le ciblage de futures molécules pharmaceutiques, le diagnostic, la médecine personnalisée et le génomique, la chirurgie, la surveillance des patients atteints de maladies chroniques… Babylon Health avec son chatbot IA a été valorisée à 1,8 milliards d’euros en 2019. Les ventes du marché du chatbot en santé ont été estimées à 33 millions d’euros en 2018. Accenture prévoit néanmoins que l’IA atteindra 5,9 milliards d’euros en 2021.</p>
<p>La réalité virtuelle (RV) peut produire un bénéfice tangible, en transportant l’utilisateur à une autre situation, grâce aux contenus visionnés, car elle modifie sa perception et lui permet d’apprendre. Chez le professionnel de santé, la réalité virtuelle a son utilité dans la formation initiale et continue ainsi que pour la simulation de gestes et d’interventions chirurgicales. C’est cet aspect qui est le plus présent dans l’actualité. Chez le patient, mais nous entendons moins en parler, la réalité virtuelle peut avoir un impact très intéressant, puisqu’elle agit sur la douleur, les phobies, l’anxiété, la dépression, des troubles de la mémoire et la démence. Elle peut aussi accélérer la ré-éducation et la réhabilitation. Le marché global de la RV en santé a été estimée à 230 millions d’euros en 2018 et pourrait atteindre 3 milliards d’euros en 2027.</p>

<p>Blockchain, télémédecine et IoT
La blockchain est également «tendance», car elle pourrait répondre à la demande de plus de transparence et confiance concernant les données en santé. Une plateforme blockchain doit permettre de mieux gérer les données, car la modification d’une donnée enregistrée, comme par exemple, le consentement d’un patient, les données d’un dossier médical patient, la chaîne d’approvisionnement du médicament, n’est pas possible sans rompre la blockchain. Ce marché a été estimé à 40 millions d’euros en 2017 et pourrait croitre à 67,1% par an (n’oublions pas le décimal ;-) selon certains, jusqu’en 2023.</p>

<p>En même temps, la télémédecine, une technologie simple qui existe depuis des décennies, voire des siècles selon la définition que l’on retient, arrive peut-être enfin à maturité! Sur le plan mondial en B2B, il y a le marché des télé-expertises (téléradiologie, télépathologie, télécardiologie, télédermatologie, …) et sur le plan B2C, il y a la consultation à distance en temps réel du patient, ainsi que les kits de diagnostic à domicile, encore peu développés en France. La télémédecine bénéficie de la tendance «service sur demande, à toute heure, dans tout lieu» favorisé par le numérique. Le marché de la télémédecine pourrait atteindre 27 milliards d’euros en 2026. Elle serait en troisième position de la santé digitale, après un autre marché quadragénaire, celui du dossier médical électronique, estimé d’atteindre 34 milliards en 2025!</p>

<p>Bientôt le décollage du marché des applications mobiles?
Les applications mobiles en santé se comptent en centaines de milliers, dont beaucoup de gratuites et peu qui atteignent un nombre d’utilisateurs significatifs. Le marché pourrait néanmoins atteindre 100 milliards d’euros en 2025. Quant aux objets connectés en santé, typiquement gérés par une application mobile, l’estimation est de l’ordre de 480 milliards d’euros.

<p>Plusieurs de ces marches se chevauchent. Une application mobile peut servir seule ou pour faire une téléconsultation voire pour gérer un objet connecté, comme nous venons de le voir. L’intelligence artificielle s’applique de façon transversale. La robotique en chirurgie et la nanotechnologie pourraient aussi être citées. Mais, les estimations sont trop variables.</p>
